config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#index'

  get 'about' => 'pages#about'
  get 'simulation' => 'simulation#simulate'
  get 'download' => 'simulation#export'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
  def about

  end
end

app/controllers/simulation_controller.rb
require_relative '../../lib/interval_method'
require_relative '../../lib/neiman_method'
require_relative '../../lib/metropolis_method'
require_relative '../../lib/math_f'
include MathF
class SimulationController < ApplicationController
  def simulate
    @lambda = params[:lambda].to_f
    @count = params[:count].to_i
    @k = params[:k].to_i
    redirect_to root_path if @lambda <= 0.0 || @count <= 0 || @count > 100_000 || @k < 0 || @k > 21

    @pmf_distribution = get_pmf_distribution(@lambda, @k)
    @theory = {
      'mode' => get_mode_theory(@lambda),
      'expected_value' => get_expected_value_theory(@lambda),
      'dispersion' => get_dispersion_theory(@lambda),
      "lambda" => @lambda,
      "n" => @count
    }

    interval_m = IntervalMethod.new
    @interval_method_hash = interval_m.generate(@lambda, @k, @count)
    e_v = get_expected_value(@interval_method_hash)
    @interval_method = {
      'mode' => get_mode(@interval_method_hash),
      'expected_value' => e_v,
      'dispersion' => get_dispersion(@interval_method_hash, e_v),
      "lambda" => @lambda,
      "n" => @count
    }

    neiman_method = NeimanMethod.new
    @neiman_method_hash = neiman_method.generate(@lambda, @k, @count)
    e_v = get_expected_value(@neiman_method_hash)
    @neiman_method = {
      'mode' => get_mode(@neiman_method_hash),
      'expected_value' => e_v,
      'dispersion' => get_dispersion(@neiman_method_hash, e_v),
      "lambda" => @lambda,
      "n" => @count
    }

    metropolis_method = MetropolisMethod.new
    @metropolis_method_hash = metropolis_method.generate(@lambda, @k, @count)
    e_v = get_expected_value(@metropolis_method_hash)
    @metropolis_method = {
      'mode' => get_mode(@metropolis_method_hash),
      'expected_value' => e_v,
      'dispersion' => get_dispersion(@metropolis_method_hash, e_v),
      "lambda" => @lambda,
      "n" => @count
    }

    @data = {
      "theory" => [@pmf_distribution, @theory],
      "interval_m" => [@interval_method_hash, @interval_method],
      "neiman_m" => [@neiman_method_hash, @neiman_method],
      "metropolis_m" => [@metropolis_method_hash, @metropolis_method],
    }

    export_to_file
  end

  def export
    send_file "data.xlsx", :disposition => 'attachment' if File.exist?("data.xlsx")
  end

  private

  def export_to_file
    Axlsx::Package.new do |p|
      @data.keys.each do |key|
        p.workbook.add_worksheet(:name => "#{key}") do |sheet|
          values = @data[key]
          hash = values[0]
          param = values[1]
          sheet.add_row(["λ = ", param['lambda'],  "n = ", param['n']])
          sheet.add_row(["k", "P(k)"])
          hash.each do |k, v|
            sheet.add_row([k, "%0.5f" % v])
          end
          sheet.add_row(%w{ })
          sheet.add_row(["Expected value:", "%0.5f" % param['expected_value']])
          sheet.add_row(["Mode:", "%0.5f" % param['mode']])
          sheet.add_row(["Dispersion:", "%0.5f" % param['dispersion']])
        end
      end
      p.serialize('data.xlsx', 'w+')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/simulation_helper.rb
module SimulationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container py-3">
    <header>
      <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <span class="d-flex align-items-center text-dark text-decoration-none">
          <span class="fs-4">Генератор випадкової величини розподілу Пуассона</span>
        </span>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <span class="me-3 py-2 text-dark text-decoration-none"><%= link_to "Головна сторінка", root_path %></span>
          <span class="py-2 text-dark text-decoration-none"><%= link_to "Про розподіл", about_path %></span>
        </nav>
      </div>
    </header>
    <main
    <%= yield %>
    </main>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<p class="fs-1">
  <h1>Роздоділ Пуассона</h1>
</p>
<p class="text-justify fs-5">
  Розподіл Пуассона – це дискретний розподіл ймовірностей, який виражає ймовірність заданого числа подій, що відбуваються в фіксованому інтервалі часу або простору, якщо ці події відбуваються з відомою середньою постійною швидкістю і незалежно від часу з моменту останньої події.
  Розподіл Пуассона також може бути використаний для кількості подій в інших визначених типах інтервалів, таких як відстань, площа або об'єм.
</p>
<p class="text-justify fs-5">
  Розподіл Пуассона може бути застосований до систем з великим числом можливих подій, кожне з яких рідко зустрічається.
  Кількість таких подій, які відбуваються протягом фіксованого часового проміжку, при правильних обставинах є випадковим числом з розподілом Пуассона.
</p>
<p class="text-justify fs-5">
  Розподіл Пуассона є дійсним, якщо вірні наступні припущення:<br>
</p>
  <ul class="text-justify fs-5">
    <li>k – кількість разів, коли подія відбувається в інтервалі, k може приймати значення 0, 1, 2, ... .</li>
    <li>Настання однієї події ніяк не впливає на ймовірність того, що відбудеться друга подія. Тобто події відбуваються самостійно.</li>
    <li>Середня швидкість, з якою відбуваються події, не залежить від будь-яких подій. Для простоти це зазвичай вважається постійним.</li>
    <li>Дві події не можуть відбутися в абсолютно однакову мить; натомість на кожному дуже маленькому підінтервалі або відбувається рівно одна подія, або жодної</li>
  </ul>
<p class="text-justify fs-5">
  Випадкова величина X називається розподіленою за законом Пуассона з параметром λ, якщо для неї виконується рівність:
</p>
<p class="text-center fs-5">
  <%= image_tag("PMF_function.png") %>
</p>
<p class="text-justify fs-5">
  де k – число входжень (k = 0, 1, 2 …).
</p>
<p class="text-justify fs-5">
  Графік густини розподілу ймовірностей наведено на рисунку 1.1
</p>
<p class="text-center fs-5">
  <br><%= image_tag("Poisson_pmf.svg") %><br>
  Рисунок 1.1 – Густина розподілу ймовірностей (PMF)
</p>
<p class="text-justify fs-5">
  В свою чергу функція розподілу ймовірностей (CDF) має наступний вигляд:
</p>
<p class="text-center">
  <%= image_tag("CDF_function.png") %>
</p>
<p class="text-justify fs-5">де Г(x, y) – верхня неповна Гамма функція, [k]– ціла частина числа k. Графік функції розподілу ймовірностей (CDF) наведено на рисунку 1.2</p>
<p class="text-center fs-5">
  <br><%= image_tag("Poisson_cdf.svg") %><br>
  Рисунок 1.2 – Функції розподілу ймовірностей (CDF)
</p>
<p class="text-justify fs-5">
  Мода розподілу Пуассона знаходиться за формулою:
  <p class="text-center">
    <%= image_tag("Mode.png") %>
  </p>
</p>
<p class="text-justify fs-5">
  Додатне дійсне число λ дорівнює математичному сподіванню X, а також її дисперсії:
</p>
<p class="text-center">
  <%= image_tag("Dispersion_and_expected_value.png") %>
</p>

app/views/pages/index.html.erb
<h1 class="fs-5">Параметри генератора розподілу Пуассона</h1><p></p>
<%= form_with url: simulation_path, method: "get", :class => 'form-group' do |f| %>
  <%= f.number_field :lambda, :class =>"form-control", required: true, in: 0.0..Float::MAX, step: 0.01, placeholder: "λ" %> <br>
  <%= f.number_field :k, :class =>"form-control", required: true, in: 0..21, step: 1,  placeholder: "k" %> <br>
  <%= f.number_field :count, :class =>"form-control", required: true, in: 1..1000000, step: 1,  placeholder: "N" %> <br>
  <%= f.submit "Симуляція", :class => "btn btn-success"  %>
<% end %>

app/views/simulation/simulate.erb
<!--chartkick-->
<%#= line_chart @data, empty: "No data" %>
<h1>Метод інтервалів</h1>
<%= line_chart [
                 {name: "Теоретичні значення", data: @pmf_distribution},
                 {name: "Практичні значення", data: @interval_method_hash}
               ], label: 'PMF', xtitle: 'k', ytitle: 'P(x = k)', height: "500px" %>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">λ</th>
      <th scope="col">k</th>
      <th scope="col">PMF</th>
      <th scope="col">Отримані значення</th>
      <th scope="col">Похибка</th>
    </tr>
  </thead>
  <% (0..@k).each do |i| %>
    <tr>
      <td><%= @lambda %></td>
      <td><%= i %></td>
      <td><%= "%0.7f" % @pmf_distribution[i] %></td>
      <td><%= "%0.7f" % @interval_method_hash[i] %></td>
      <td><%= "%0.7f" % (@pmf_distribution[i] - @interval_method_hash[i]).abs %></td>
    </tr>
  <% end %>
</table>
<br>
<p class="fs-5">
  Теоретичне математичне очікування: <%= "%0.5f" % @theory['expected_value'] %> <br>
  Практичне математичне очікування: <%= "%0.5f" % @interval_method['expected_value'] %> <br>
</p>
<p class="fs-5">
  Теоретичне значення моди: <%= "%0.5f" % @theory['mode'] %> <br>
  Практична значення моди: <%= "%0.5f" % @interval_method['mode'] %> <br>
</p>
<p class="fs-5">
  Теоретичне значення дисперсії: <%= "%0.5f" % @theory['dispersion'] %> <br>
  Практичне значення дисперсії: <%= "%0.5f" % @interval_method['dispersion'] %> <br>
</p>
<br>
<h1>Метод Неймана</h1>
<%= line_chart [
                 {name: "Теоретичні значення", data: @pmf_distribution},
                 {name: "Практичні значення", data: @neiman_method_hash}
               ], label: 'PMF', xtitle: 'k', ytitle: 'P(x = k)', height: "500px" %>
<br>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">λ</th>
    <th scope="col">k</th>
    <th scope="col">PMF</th>
    <th scope="col">Отримані значення</th>
    <th scope="col">Похибка</th>
  </tr>
  </thead>
  <% (0..@k).each do |i| %>
    <tr>
      <td><%= @lambda %></td>
      <td><%= i %></td>
      <td><%= "%0.7f" % @pmf_distribution[i] %></td>
      <td><%= "%0.7f" % @neiman_method_hash[i] %></td>
      <td><%= "%0.7f" % (@pmf_distribution[i] - @neiman_method_hash[i]).abs %></td>
    </tr>
  <% end %>
</table>
<br>
<p class="fs-5">
  Теоретичне математичне очікування: <%= "%0.5f" % @theory['expected_value'] %> <br>
  Практичне математичне очікування: <%= "%0.5f" % @neiman_method['expected_value'] %> <br>
</p>
<p class="fs-5">
  Теоретичне значення моди: <%= "%0.5f" % @theory['mode'] %> <br>
  Практична значення моди: <%= "%0.5f" % @neiman_method['mode'] %> <br>
</p>
<p class="fs-5">
  Теоретичне значення дисперсії: <%= "%0.5f" % @theory['dispersion'] %> <br>
  Практичне значення дисперсії: <%= "%0.5f" % @neiman_method['dispersion'] %> <br>
</p>
<br>
<h1>Алгоритм Метрополіса</h1>
<%= line_chart [
                 {name: "Теоретичні значення", data: @pmf_distribution},
                 {name: "Практичні значення", data: @metropolis_method_hash}
               ], label: 'PMF', xtitle: 'k', ytitle: 'P(x = k)', height: "500px" %>
<br>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">λ</th>
    <th scope="col">k</th>
    <th scope="col">PMF</th>
    <th scope="col">Отримані значення</th>
    <th scope="col">Похибка</th>
  </tr>
  </thead>
  <% (0..@k).each do |i| %>
    <tr>
      <td><%= @lambda %></td>
      <td><%= i %></td>
      <td><%= "%0.7f" % @pmf_distribution[i] %></td>
      <td><%= "%0.7f" % @metropolis_method_hash[i] %></td>
      <td><%= "%0.7f" % (@pmf_distribution[i] - @metropolis_method_hash[i]).abs %></td>
    </tr>
  <% end %>
</table>
<br>
<p class="fs-5">
  Теоретичне математичне очікування: <%= "%0.5f" % @theory['expected_value'] %> <br>
  Практичне математичне очікування: <%= "%0.5f" % @metropolis_method['expected_value'] %> <br>
</p>
<p class="fs-5">
  Теоретичне значення моди: <%= "%0.5f" % @theory['mode'] %> <br>
  Практична значення моди: <%= "%0.5f" % @metropolis_method['mode'] %> <br>
</p>
<p class="fs-5">
  Теоретичне значення дисперсії: <%= "%0.5f" % @theory['dispersion'] %> <br>
  Практичне значення дисперсії: <%= "%0.5f" % @metropolis_method['dispersion'] %> <br>
</p>
<br>
<h1>Гістограма для методів розподілу</h1>
<%= column_chart [
                    { name: 'Теоретичні значення', data: @pmf_distribution },
                    { name: 'Метод інтервалів', data: @interval_method_hash },
                    {name: "Метод Неймана", data: @neiman_method_hash },
                    {name: "Алгоритм Метрополіса", data: @metropolis_method_hash }
], height:"500px", xtitle: 'k', ytitle: 'Pi / Pn'%>
<br>
<span class="py-2 text-dark text-decoration-none"><%= link_to "Завантажити дані", download_path %></span>